# Use 'generic' to be able to override CC/CXX for clang
language: generic

# Use a release with a longer normal LTS
dist: xenial

matrix:
  include:
    - compiler: mingw-x64
      addons: true
      env: CROSS_COMPILE=x86_64-w64-mingw32- CFLAGS="-D_WIN32_WINNT=0x0501"
    - compiler: gcc
      env: CC=gcc-9 CXX=g++-9

before_install:
  - |
     if [ "$CC" = gcc-9 ]; then
       # Install a more recent gcc than the default
       sudo apt-get install -y gcc-9
     elif [ "$CC" = clang-6.0 ]; then
       # Install a more recent clang than the default
       sudo apt-get install -y clang-6.0
     elif [ "$CROSS_COMPILE" = i686-w64-mingw32- ]; then
       sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
     elif [ "$CROSS_COMPILE" = x86_64-w64-mingw32- ]; then
       sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
     fi

script:
  - |
     make

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial
